services:
  - type: web
    name: shopzone
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend --bind 0.0.0.0:$PORT --workers 1 --timeout 60 app_supabase:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        value: "https://khacikjsbltpkqpcjmfn.supabase.co"
      - key: SUPABASE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoYWNpa2pzYmx0cGtxcGNqbWZuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE4NzI3NCwiZXhwIjoyMDg3NzYzMjc0fQ.Yc6FhGGKaXEcd9j2aTie-mTnzmd7v-t-FeFOql0GE1c"
