services:
  - type: web
    name: shopzone
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app_supabase:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
